### ISSUE TITLE
Exported Class

### ISSUE THREAD

**Issue by ISNIT0** [requirex/requirex#15]
Do we really think `System` is the best thing to export? Maybe `RX` or even both?

**Comment by jjrv** [comment]
It's for compatibility with SystemJS, also mentioned in passing in the [WHATWG Loader spec](https://whatwg.github.io/loader/#browser). RX could get confused with [RxJS](https://rxjs-dev.firebaseapp.com/)... Otherwise I'd prefix everything with it :P

**Comment by jjrv** [comment]
It's not like this would be very compatible with SystemJS overall though, just trying to support the module format which TypeScript is also capable of emitting. It calls `System.register` but there isn't really any reason other code would need to see `System`, just like only AMD code currently sees `define`.

You will also find similarities to the [config API](https://github.com/systemjs/systemjs/blob/0.21/docs/config-api.md) and [SystemJS API](https://github.com/systemjs/systemjs/blob/0.21/docs/system-api.md). Or their latest [example usage](https://github.com/systemjs/systemjs#example-usage).

Seeing `System.import()` just might look familiar in some circles. Not sure if always in a good way 🤔

Love it myself. This project wouldn't exist without SystemJS forging the path first.
